  
version: '3.4'

services:
  kafka:
    container_name: klc-kafka
    image: landoop/kafka-lenses-dev
    hostname: klc-kafka
    ports:
      - 3030:3030
      - 9092:9092
      - 2181:2181
      - 8081:8081
    environment:
       - ADV_HOST=127.0.0.1
       - LICENSE_URL=${EMAIL}
    labels:
      mrjamiebowman: kafka-log-compaction